version: '3.8'

services:
  myapp:
    # build: .
    image: bpt20062009/vietnam-fes
    container_name: myapp
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    stdin_open: true
    tty: true